/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.FileData;
import Model.Phong;
import Model.PhongLyThuyet;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author PC
 */
public class DanhGiaLyThuyet extends javax.swing.JFrame {

    DefaultTableModel model;
    PhongLyThuyet x;
    ArrayList<Phong> ds = new ArrayList<>(new FileData<Phong>().readFile("Phong.txt"));
    /**
     * Creates new form DanhGiaLyThuyet
     */
    public DanhGiaLyThuyet() {
        initComponents();
        model = (DefaultTableModel) tbBangDanhGiaPhongLyThuyet.getModel();
        tbBangDanhGiaPhongLyThuyet.getColumnModel().getColumn(0).setPreferredWidth(20);
        tbBangDanhGiaPhongLyThuyet.getColumnModel().getColumn(1).setPreferredWidth(60);
        tbBangDanhGiaPhongLyThuyet.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbBangDanhGiaPhongLyThuyet.getColumnModel().getColumn(3).setPreferredWidth(20);    
        setUpScoreColumn(tbBangDanhGiaPhongLyThuyet, tbBangDanhGiaPhongLyThuyet.getColumnModel().getColumn(tbBangDanhGiaPhongLyThuyet.getColumnCount() - 1));
    }
    
    public DanhGiaLyThuyet(PhongLyThuyet x){
        initComponents();
        this.x = x;
        tbBangDanhGiaPhongLyThuyet.getColumnModel().getColumn(0).setPreferredWidth(20);
        tbBangDanhGiaPhongLyThuyet.getColumnModel().getColumn(1).setPreferredWidth(60);
        tbBangDanhGiaPhongLyThuyet.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbBangDanhGiaPhongLyThuyet.getColumnModel().getColumn(3).setPreferredWidth(20);    
        setUpScoreColumn(tbBangDanhGiaPhongLyThuyet, tbBangDanhGiaPhongLyThuyet.getColumnModel().getColumn(tbBangDanhGiaPhongLyThuyet.getColumnCount() - 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBangDanhGiaPhongLyThuyet = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 153));
        jLabel1.setText("Bảng đánh giá  tại phòng lý thuyết");

        tbBangDanhGiaPhongLyThuyet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbBangDanhGiaPhongLyThuyet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Bàn/Ghế", "Có sạch sẽ và được sắp xếp gọn gàng không?", null},
                { new Integer(2), "Bảng ", "Có sạch sẽ và giữ ở điều kiện tốt không?", null},
                { new Integer(3), "Điều hòa/Quạt", "Có sạch sẽ, an toàn và được bố trí hợp lý không? Còn sử dụng tốt hay không?  ", null},
                { new Integer(4), "Sàn nhà", "Có sạch sẽ và được giữ gìn tốt không? Có rác trên sàn không? ", null},
                { new Integer(5), "Thùng rác", "Có sạch sẽ và đặt ở vị trí hợp lý không? ", null},
                { new Integer(6), "Tiết kiệm điẹn năng", "Có tắt các thiết bị điện khi không sử dụng phòng không?", null}
            },
            new String [] {
                "STT", "Muc", "Các điẻm kiểm tra", "Điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbBangDanhGiaPhongLyThuyet);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Đánh giá");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(72, 72, 72)
                .addComponent(jButton2)
                .addGap(436, 436, 436))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Xử lý sự kiện đánh giá và lưu lại đối tượng tương ứng
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int columnIndex = 3;
        if(tbBangDanhGiaPhongLyThuyet.getValueAt(0, columnIndex) == null || tbBangDanhGiaPhongLyThuyet.getValueAt(1, columnIndex) == null ||
                tbBangDanhGiaPhongLyThuyet.getValueAt(2, columnIndex) == null || tbBangDanhGiaPhongLyThuyet.getValueAt(3, columnIndex) == null ||
                tbBangDanhGiaPhongLyThuyet.getValueAt(4, columnIndex) == null || tbBangDanhGiaPhongLyThuyet.getValueAt(5, columnIndex) == null){
            JOptionPane.showMessageDialog(null, "Các điểm đánh giá phải được đánh giá hết ạ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ds.remove(x);
        try {
            x.setDiemBanGhe(Short.parseShort(tbBangDanhGiaPhongLyThuyet.getValueAt(0, columnIndex).toString()));
            x.setDiemBang(Short.parseShort(tbBangDanhGiaPhongLyThuyet.getValueAt(1, columnIndex).toString()));
            x.setDiemDieuHoaQuat(Short.parseShort(tbBangDanhGiaPhongLyThuyet.getValueAt(2, columnIndex).toString()));
            x.setDiemSanNha(Short.parseShort(tbBangDanhGiaPhongLyThuyet.getValueAt(3, columnIndex).toString()));
            x.setDiemThungRac(Short.parseShort(tbBangDanhGiaPhongLyThuyet.getValueAt(4, columnIndex).toString()));
            x.setDiemTietKiemDienNang(Short.parseShort(tbBangDanhGiaPhongLyThuyet.getValueAt(5, columnIndex).toString()));
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        ds.add(x);
        new FileData<Phong>().writeFile(ds, "Phong.txt");
        JOptionPane.showMessageDialog(null, "Đánh giá thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        new NhapPhongDanhGia().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setUpScoreColumn(JTable table,
                                 TableColumn loaiP) {
        //Set up the editor for the sport cells.
        JComboBox comboBox = new JComboBox();
        
        comboBox.addItem("0");
        comboBox.addItem("1");
        comboBox.addItem("2");
        comboBox.addItem("3");
        comboBox.addItem("4");
        loaiP.setCellEditor(new DefaultCellEditor(comboBox));
        //Set up tool tips for the sport cells.
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setToolTipText("Click for combo box");
        loaiP.setCellRenderer(renderer);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhGiaLyThuyet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhGiaLyThuyet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhGiaLyThuyet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhGiaLyThuyet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhGiaLyThuyet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbBangDanhGiaPhongLyThuyet;
    // End of variables declaration//GEN-END:variables
}
