/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.FileData;
import Model.Phong;
import Model.VanPhong;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author PC
 */
public class DanhGiaVanPhong extends javax.swing.JFrame {

    VanPhong x;
    ArrayList<Phong> ds = new ArrayList<>(new FileData<Phong>().readFile("Phong.txt"));
    /**
     * Creates new form DanhGiaVanPhong
     */
    public DanhGiaVanPhong() {
        initComponents();
    }
    
    public DanhGiaVanPhong(VanPhong x){
        initComponents();
        this.x = x;
        setUpScoreColumn(tbBangDanhGiaVanPhong, tbBangDanhGiaVanPhong.getColumnModel().getColumn(tbBangDanhGiaVanPhong.getColumnCount() - 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbBangDanhGiaVanPhong = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbBangDanhGiaVanPhong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbBangDanhGiaVanPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Văn phòng phẩm", "Có sạch sẽ và đặt ở vị trí hợp lý không? ", null},
                { new Integer(2), "Thùng rác", "Có sạch sẽ và đặt ở vị trí hợp lý không? ", null},
                { new Integer(3), "Tài  liệu bàn", "Tài liệu có xếp thành đống trên bàn không?", null},
                { new Integer(4), "Trang phục", "Có mặc trang phục và vẻ ngoài phù hợp hay không?", null},
                { new Integer(5), "Thẻ", "Tất cả nhân viên có đeo thẻ trong giờ làm việc hay không?", null}
            },
            new String [] {
                "STT", "Muc", "Các điẻm kiểm tra", "Điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbBangDanhGiaVanPhong);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Đánh giá");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 153));
        jLabel1.setText("Bảng đánh giá  tại phòng văn phòng");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(70, 70, 70)
                        .addComponent(jButton3)
                        .addGap(333, 333, 333))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Xử lý sư kiện văn phòng
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int columnIndex = 3;
        if(tbBangDanhGiaVanPhong.getValueAt(0, columnIndex) == null || tbBangDanhGiaVanPhong.getValueAt(1, columnIndex) == null ||
                tbBangDanhGiaVanPhong.getValueAt(2, columnIndex) == null || tbBangDanhGiaVanPhong.getValueAt(3, columnIndex) == null ||
                tbBangDanhGiaVanPhong.getValueAt(4, columnIndex) == null){
            JOptionPane.showMessageDialog(null, "Các điểm đánh giá phải được đánh giá hết ạ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ds.remove(x);
        x.setDiemVanPhongPham(Short.parseShort(tbBangDanhGiaVanPhong.getValueAt(0, columnIndex).toString()));
        x.setDiemThungRac(Short.parseShort(tbBangDanhGiaVanPhong.getValueAt(1, columnIndex).toString()));
        x.setDiemTaiLieuBan(Short.parseShort(tbBangDanhGiaVanPhong.getValueAt(2, columnIndex).toString()));
        x.setDiemTrangPhuc(Short.parseShort(tbBangDanhGiaVanPhong.getValueAt(3, columnIndex).toString()));
        x.setDiemThe(Short.parseShort(tbBangDanhGiaVanPhong.getValueAt(4, columnIndex).toString()));
        ds.add(x);
        new FileData<Phong>().writeFile(ds, "Phong.txt");
        JOptionPane.showMessageDialog(null, "Đánh giá thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        new NhapPhongDanhGia().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhGiaVanPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhGiaVanPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhGiaVanPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhGiaVanPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhGiaVanPhong().setVisible(true);
            }
        });
    }

    public void setUpScoreColumn(JTable table,
                                 TableColumn loaiP) {
        //Set up the editor for the sport cells.
        JComboBox comboBox = new JComboBox();
        
        comboBox.addItem("0");
        comboBox.addItem("1");
        comboBox.addItem("2");
        comboBox.addItem("3");
        comboBox.addItem("4");
        loaiP.setCellEditor(new DefaultCellEditor(comboBox));
        //Set up tool tips for the sport cells.
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setToolTipText("Click for combo box");
        loaiP.setCellRenderer(renderer);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbBangDanhGiaVanPhong;
    // End of variables declaration//GEN-END:variables
}
