/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.FileData;
import Model.Phong;
import Model.PhongLyThuyet;
import Model.PhongThucHanh;
import Model.VanPhong;
import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author PC
 */
public class MenuUser extends javax.swing.JFrame {

    String taiKhoan;
    ArrayList<Phong> ds = new ArrayList<>(new FileData<Phong>().readFile("Phong.txt"));
    /**
     * Creates new form MenuUser
     */
    public MenuUser() {
        initComponents();
    }
    
    public MenuUser(String taiKhoan) {
        initComponents();
        this.taiKhoan = taiKhoan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btXemThongTin = new javax.swing.JButton();
        btXemPhieuDanhGia = new javax.swing.JButton();
        btSuaThongTin = new javax.swing.JButton();
        btDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("Chúc mừng bạn đăng nhập vào hệ thống thành công");

        btXemThongTin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btXemThongTin.setText("Xem thông tin");
        btXemThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btXemThongTinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btXemThongTinMouseExited(evt);
            }
        });
        btXemThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXemThongTinActionPerformed(evt);
            }
        });

        btXemPhieuDanhGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btXemPhieuDanhGia.setText("Xem phiếu đánh giá");
        btXemPhieuDanhGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btXemPhieuDanhGiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btXemPhieuDanhGiaMouseExited(evt);
            }
        });
        btXemPhieuDanhGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXemPhieuDanhGiaActionPerformed(evt);
            }
        });

        btSuaThongTin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSuaThongTin.setText("Sửa thông tin");
        btSuaThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSuaThongTinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSuaThongTinMouseExited(evt);
            }
        });
        btSuaThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaThongTinActionPerformed(evt);
            }
        });

        btDangXuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btDangXuat.setText("Đăng xuất");
        btDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDangXuatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btXemThongTin)
                .addGap(91, 91, 91)
                .addComponent(btXemPhieuDanhGia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSuaThongTin)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(btDangXuat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btXemThongTin)
                    .addComponent(btXemPhieuDanhGia)
                    .addComponent(btSuaThongTin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btDangXuat)
                .addGap(131, 131, 131))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btXemThongTinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXemThongTinMouseEntered
        // TODO add your handling code here:
        btXemThongTin.setBackground(Color.GREEN);
        btXemThongTin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btXemThongTin.setForeground(Color.WHITE);
    }//GEN-LAST:event_btXemThongTinMouseEntered

    private void btXemThongTinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXemThongTinMouseExited
        // TODO add your handling code here:
        btXemThongTin.setForeground(UIManager.getColor("control"));
        btXemThongTin.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        btXemThongTin.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btXemThongTinMouseExited

    private void btXemPhieuDanhGiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXemPhieuDanhGiaMouseEntered
        // TODO add your handling code here:
        btXemPhieuDanhGia.setBackground(Color.GREEN);
        btXemPhieuDanhGia.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btXemPhieuDanhGia.setForeground(Color.white);
    }//GEN-LAST:event_btXemPhieuDanhGiaMouseEntered

    private void btXemPhieuDanhGiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXemPhieuDanhGiaMouseExited
        // TODO add your handling code here:
        btXemPhieuDanhGia.setBackground(UIManager.getColor("control"));
        btXemPhieuDanhGia.setForeground(UIManager.getColor("control"));
        btXemPhieuDanhGia.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btXemPhieuDanhGiaMouseExited

    private void btSuaThongTinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSuaThongTinMouseEntered
        // TODO add your handling code here:
        btSuaThongTin.setForeground(Color.WHITE);
        btSuaThongTin.setBackground(Color.GREEN);
        btSuaThongTin.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btSuaThongTinMouseEntered

    private void btSuaThongTinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSuaThongTinMouseExited
        // TODO add your handling code here:
        btSuaThongTin.setBackground(UIManager.getColor("control"));
        btSuaThongTin.setForeground(UIManager.getColor("control"));
        btSuaThongTin.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btSuaThongTinMouseExited

    private void btDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangXuatMouseEntered
        // TODO add your handling code here:
        btDangXuat.setForeground(Color.WHITE);
        btDangXuat.setBackground(Color.RED);
        btDangXuat.setCursor(new Cursor(Cursor.HAND_CURSOR));        
    }//GEN-LAST:event_btDangXuatMouseEntered

    private void btDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangXuatMouseExited
        // TODO add your handling code here:
        btDangXuat.setBackground(UIManager.getColor("control"));
        btDangXuat.setForeground(UIManager.getColor("control"));
        btDangXuat.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));        
    }//GEN-LAST:event_btDangXuatMouseExited

    //Xử lý sự kiện đăng xuất
    private void btDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangXuatMouseClicked
        this.dispose();
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_btDangXuatMouseClicked

    private void btXemThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXemThongTinActionPerformed
        // TODO add your handling code here:
        XemThongTin x = new XemThongTin(taiKhoan);
        x.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btXemThongTinActionPerformed
    //Xử lý sự kiện sửa thông tin phòng
    private void btSuaThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaThongTinActionPerformed
        // TODO add your handling code here:
        new SuaThongTin(taiKhoan).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btSuaThongTinActionPerformed

    private void btXemPhieuDanhGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXemPhieuDanhGiaActionPerformed
        // TODO add your handling code here:
        if(getPhongLyThuyet() instanceof PhongLyThuyet && getPhongLyThuyet().tongDiem() > 0){
            new PhieuDanhGiaLyThuyet(getPhongLyThuyet()).setVisible(true);
            this.dispose();
        }else if(getPhongThucHanh() instanceof PhongThucHanh && getPhongThucHanh().tongDiem() > 0){
            new PhieuDanhGiaThucHanh(getPhongThucHanh()).setVisible(true);
            dispose();
        }else if(getVanPhong() instanceof VanPhong && getVanPhong().tongDiem() > 0){
            new PhieuDanhGiaVanPhong(getVanPhong()).setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Phòng của bạn chưa được đánh giá!");
        }
//        }else if(getPhong() instanceof PhongThucHanh){
//            //new PhieuDanhGiaThucHanh(PhongThucHanh)getPhong()).setVisible(true);
//            this.dispose();
//        }else this.dispose();
    }//GEN-LAST:event_btXemPhieuDanhGiaActionPerformed

    //Lấy đối tượng hiện tai
    public PhongLyThuyet getPhongLyThuyet(){
        for (Phong d : ds) {
            if(d.getTk().getTaiKhoan().equals(taiKhoan) && d instanceof PhongLyThuyet)
                return (PhongLyThuyet)d;
        }
        return null;
    }
    
    public PhongThucHanh getPhongThucHanh(){
        for (Phong d : ds) {
            if(d.getTk().getTaiKhoan().equals(taiKhoan) && d instanceof PhongThucHanh)
                return (PhongThucHanh)d;
        }
        return null;
    }
    
    public VanPhong getVanPhong(){
        for (Phong d : ds) {
            if(d.getTk().getTaiKhoan().equals(taiKhoan) && d instanceof VanPhong)
                return (VanPhong)d;
        }
        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangXuat;
    private javax.swing.JButton btSuaThongTin;
    private javax.swing.JButton btXemPhieuDanhGia;
    private javax.swing.JButton btXemThongTin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
