/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.UIManager;

/**
 *
 * @author PC
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btQuanLyCacPhong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btDanhGiaPhong = new javax.swing.JButton();
        btXemDiemCacPhong = new javax.swing.JButton();
        btDangXuat = new javax.swing.JButton();
        btYeuCau = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btQuanLyCacPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btQuanLyCacPhong.setText("Quản lý");
        btQuanLyCacPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btQuanLyCacPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btQuanLyCacPhongMouseExited(evt);
            }
        });
        btQuanLyCacPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuanLyCacPhongActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("Đăng nhập quán lý hệ thống thành công");

        btDanhGiaPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btDanhGiaPhong.setText("Đánh giá");
        btDanhGiaPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDanhGiaPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDanhGiaPhongMouseExited(evt);
            }
        });
        btDanhGiaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDanhGiaPhongActionPerformed(evt);
            }
        });

        btXemDiemCacPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btXemDiemCacPhong.setText("Xem đánh giá");
        btXemDiemCacPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btXemDiemCacPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btXemDiemCacPhongMouseExited(evt);
            }
        });
        btXemDiemCacPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXemDiemCacPhongActionPerformed(evt);
            }
        });

        btDangXuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btDangXuat.setText("Đăng xuất");
        btDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDangXuatMouseExited(evt);
            }
        });

        btYeuCau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btYeuCau.setText("Yêu cầu");
        btYeuCau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btYeuCauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btYeuCauMouseExited(evt);
            }
        });
        btYeuCau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btYeuCauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btDangXuat)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btDanhGiaPhong)
                    .addComponent(btQuanLyCacPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btXemDiemCacPhong)
                    .addComponent(btYeuCau))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQuanLyCacPhong)
                    .addComponent(btXemDiemCacPhong))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDanhGiaPhong)
                    .addComponent(btYeuCau))
                .addGap(47, 47, 47)
                .addComponent(btDangXuat)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQuanLyCacPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuanLyCacPhongMouseEntered
        // TODO add your handling code here:
        btQuanLyCacPhong.setBackground(Color.GREEN);
        btQuanLyCacPhong.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btQuanLyCacPhong.setForeground(Color.WHITE);
    }//GEN-LAST:event_btQuanLyCacPhongMouseEntered

    private void btQuanLyCacPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuanLyCacPhongMouseExited
        // TODO add your handling code here:
        btQuanLyCacPhong.setForeground(UIManager.getColor("control"));
        btQuanLyCacPhong.setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); 
        btQuanLyCacPhong.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btQuanLyCacPhongMouseExited

    private void btDanhGiaPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDanhGiaPhongMouseEntered
        // TODO add your handling code here:
        btDanhGiaPhong.setBackground(Color.GREEN);
        btDanhGiaPhong.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btDanhGiaPhong.setForeground(Color.white);
    }//GEN-LAST:event_btDanhGiaPhongMouseEntered

    private void btDanhGiaPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDanhGiaPhongMouseExited
        // TODO add your handling code here:
        btDanhGiaPhong.setBackground(UIManager.getColor("control"));
        btDanhGiaPhong.setForeground(UIManager.getColor("control"));
        btDanhGiaPhong.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));     
    }//GEN-LAST:event_btDanhGiaPhongMouseExited

    private void btXemDiemCacPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXemDiemCacPhongMouseEntered
        // TODO add your handling code here:
        btXemDiemCacPhong.setForeground(Color.WHITE);
        btXemDiemCacPhong.setBackground(Color.GREEN);
        btXemDiemCacPhong.setCursor(new Cursor(Cursor.HAND_CURSOR));        
    }//GEN-LAST:event_btXemDiemCacPhongMouseEntered

    private void btXemDiemCacPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXemDiemCacPhongMouseExited
        // TODO add your handling code here:
        btXemDiemCacPhong.setBackground(UIManager.getColor("control"));        
        btXemDiemCacPhong.setForeground(UIManager.getColor("control"));
        btXemDiemCacPhong.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));      
    }//GEN-LAST:event_btXemDiemCacPhongMouseExited

    private void btDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangXuatMouseClicked
        new DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDangXuatMouseClicked

    private void btDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangXuatMouseEntered
        // TODO add your handling code here:
        btDangXuat.setForeground(Color.WHITE);
        btDangXuat.setBackground(Color.RED);
        btDangXuat.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btDangXuatMouseEntered

    private void btDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangXuatMouseExited
        // TODO add your handling code here:
        btDangXuat.setBackground(UIManager.getColor("control"));
        btDangXuat.setForeground(UIManager.getColor("control"));
        btDangXuat.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btDangXuatMouseExited

    //Xử lý sự kiện quản lý các loại phòng
    private void btQuanLyCacPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuanLyCacPhongActionPerformed
        // TODO add your handling code here:
        new QuanLyPhong().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btQuanLyCacPhongActionPerformed

    //Xử lý sự kiện đánh giá phòng
    private void btDanhGiaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDanhGiaPhongActionPerformed
        // TODO add your handling code here:
        new NhapPhongDanhGia().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDanhGiaPhongActionPerformed

// Xử lý sư kiện xem đánh giá 
    private void btXemDiemCacPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXemDiemCacPhongActionPerformed
        // TODO add your handling code here:
        new XemDanhGiaCacPhong().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btXemDiemCacPhongActionPerformed

    private void btYeuCauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btYeuCauMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btYeuCauMouseEntered

    private void btYeuCauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btYeuCauMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btYeuCauMouseExited

    //Xử lý sự kiện yêu cầu
    private void btYeuCauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btYeuCauActionPerformed
        // TODO add your handling code here:
        (new YeuCau()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btYeuCauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangXuat;
    private javax.swing.JButton btDanhGiaPhong;
    private javax.swing.JButton btQuanLyCacPhong;
    private javax.swing.JButton btXemDiemCacPhong;
    private javax.swing.JButton btYeuCau;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
